cd /home/amit/muse/output/activitylauncher/schemas/SINK/activitylauncher/
/home/amit/muse/output/activitylauncher/schemas/SINK/activitylauncher/gradlew clean
/home/amit/muse/output/activitylauncher/schemas/SINK/activitylauncher/gradlew assembleDebug
cd /home/amit/muse/output/activitylauncher/schemas/REACHABILITY/activitylauncher/
/home/amit/muse/output/activitylauncher/schemas/REACHABILITY/activitylauncher/gradlew clean
/home/amit/muse/output/activitylauncher/schemas/REACHABILITY/activitylauncher/gradlew assembleDebug
cd /home/amit/muse/output/activitylauncher/schemas/TAINTSINK/activitylauncher/
/home/amit/muse/output/activitylauncher/schemas/TAINTSINK/activitylauncher/gradlew clean
/home/amit/muse/output/activitylauncher/schemas/TAINTSINK/activitylauncher/gradlew assembleDebug
cd /home/amit/muse/output/activitylauncher/schemas/COMPLEXREACHABILITY/activitylauncher/
/home/amit/muse/output/activitylauncher/schemas/COMPLEXREACHABILITY/activitylauncher/gradlew clean
/home/amit/muse/output/activitylauncher/schemas/COMPLEXREACHABILITY/activitylauncher/gradlew assembleDebug
