sh clean_project_folder.sh
echo LocationShare SINK
sh LocationShare_SINK.sh
echo LocationShare REACHABILITY
sh LocationShare_REACHABILITY.sh
echo LocationShare TAINTSINK
sh LocationShare_TAINTSINK.sh
echo LocationShare COMPLEXREACHABILITY
sh LocationShare_COMPLEXREACHABILITY.sh
