cd /home/amit/muse/output/LocationShare/schemas/SINK/LocationShare/
/home/amit/muse/output/LocationShare/schemas/SINK/LocationShare/gradlew clean
/home/amit/muse/output/LocationShare/schemas/SINK/LocationShare/gradlew assembleDebug
cd /home/amit/muse/output/LocationShare/schemas/REACHABILITY/LocationShare/
/home/amit/muse/output/LocationShare/schemas/REACHABILITY/LocationShare/gradlew clean
/home/amit/muse/output/LocationShare/schemas/REACHABILITY/LocationShare/gradlew assembleDebug
cd /home/amit/muse/output/LocationShare/schemas/TAINTSINK/LocationShare/
/home/amit/muse/output/LocationShare/schemas/TAINTSINK/LocationShare/gradlew clean
/home/amit/muse/output/LocationShare/schemas/TAINTSINK/LocationShare/gradlew assembleDebug
cd /home/amit/muse/output/LocationShare/schemas/COMPLEXREACHABILITY/LocationShare/
/home/amit/muse/output/LocationShare/schemas/COMPLEXREACHABILITY/LocationShare/gradlew clean
/home/amit/muse/output/LocationShare/schemas/COMPLEXREACHABILITY/LocationShare/gradlew assembleDebug
