cd /home/amit/muse/output/Recycler/schemas/SINK/Recycler/
/home/amit/muse/output/Recycler/schemas/SINK/Recycler/gradlew clean
/home/amit/muse/output/Recycler/schemas/SINK/Recycler/gradlew assembleDebug
cd /home/amit/muse/output/Recycler/schemas/REACHABILITY/Recycler/
/home/amit/muse/output/Recycler/schemas/REACHABILITY/Recycler/gradlew clean
/home/amit/muse/output/Recycler/schemas/REACHABILITY/Recycler/gradlew assembleDebug
cd /home/amit/muse/output/Recycler/schemas/TAINTSINK/Recycler/
/home/amit/muse/output/Recycler/schemas/TAINTSINK/Recycler/gradlew clean
/home/amit/muse/output/Recycler/schemas/TAINTSINK/Recycler/gradlew assembleDebug
cd /home/amit/muse/output/Recycler/schemas/COMPLEXREACHABILITY/Recycler/
/home/amit/muse/output/Recycler/schemas/COMPLEXREACHABILITY/Recycler/gradlew clean
/home/amit/muse/output/Recycler/schemas/COMPLEXREACHABILITY/Recycler/gradlew assembleDebug
