cd /home/amit/muse/output/android-timetracker/schemas/SINK/android-timetracker/
/home/amit/muse/output/android-timetracker/schemas/SINK/android-timetracker/gradlew clean
/home/amit/muse/output/android-timetracker/schemas/SINK/android-timetracker/gradlew build
cd /home/amit/muse/output/android-timetracker/schemas/REACHABILITY/android-timetracker/
/home/amit/muse/output/android-timetracker/schemas/REACHABILITY/android-timetracker/gradlew clean
/home/amit/muse/output/android-timetracker/schemas/REACHABILITY/android-timetracker/gradlew build
cd /home/amit/muse/output/android-timetracker/schemas/TAINTSINK/android-timetracker/
/home/amit/muse/output/android-timetracker/schemas/TAINTSINK/android-timetracker/gradlew clean
/home/amit/muse/output/android-timetracker/schemas/TAINTSINK/android-timetracker/gradlew build
cd /home/amit/muse/output/android-timetracker/schemas/COMPLEXREACHABILITY/android-timetracker/
/home/amit/muse/output/android-timetracker/schemas/COMPLEXREACHABILITY/android-timetracker/gradlew clean
/home/amit/muse/output/android-timetracker/schemas/COMPLEXREACHABILITY/android-timetracker/gradlew build
