cd /home/amit/muse/output/privacyqr/schemas/SINK/privacyqr/
/home/amit/muse/output/privacyqr/schemas/SINK/privacyqr/gradlew clean
/home/amit/muse/output/privacyqr/schemas/SINK/privacyqr/gradlew assembleDebug
cd /home/amit/muse/output/privacyqr/schemas/REACHABILITY/privacyqr/
/home/amit/muse/output/privacyqr/schemas/REACHABILITY/privacyqr/gradlew clean
/home/amit/muse/output/privacyqr/schemas/REACHABILITY/privacyqr/gradlew assembleDebug
cd /home/amit/muse/output/privacyqr/schemas/TAINTSINK/privacyqr/
/home/amit/muse/output/privacyqr/schemas/TAINTSINK/privacyqr/gradlew clean
/home/amit/muse/output/privacyqr/schemas/TAINTSINK/privacyqr/gradlew assembleDebug
cd /home/amit/muse/output/privacyqr/schemas/COMPLEXREACHABILITY/privacyqr/
/home/amit/muse/output/privacyqr/schemas/COMPLEXREACHABILITY/privacyqr/gradlew clean
/home/amit/muse/output/privacyqr/schemas/COMPLEXREACHABILITY/privacyqr/gradlew assembleDebug
