cd /home/amit/muse/output/kaltura/schemas/SINK/kaltura/
/home/amit/muse/output/kaltura/schemas/SINK/kaltura/gradlew clean
/home/amit/muse/output/kaltura/schemas/SINK/kaltura/gradlew build
cd /home/amit/muse/output/kaltura/schemas/REACHABILITY/kaltura/
/home/amit/muse/output/kaltura/schemas/REACHABILITY/kaltura/gradlew clean
/home/amit/muse/output/kaltura/schemas/REACHABILITY/kaltura/gradlew build
cd /home/amit/muse/output/kaltura/schemas/TAINTSINK/kaltura/
/home/amit/muse/output/kaltura/schemas/TAINTSINK/kaltura/gradlew clean
/home/amit/muse/output/kaltura/schemas/TAINTSINK/kaltura/gradlew build
cd /home/amit/muse/output/kaltura/schemas/COMPLEXREACHABILITY/kaltura/
/home/amit/muse/output/kaltura/schemas/COMPLEXREACHABILITY/kaltura/gradlew clean
/home/amit/muse/output/kaltura/schemas/COMPLEXREACHABILITY/kaltura/gradlew build
