cd /home/amit/muse/output/cameraroll/schemas/SINK/cameraroll/
/home/amit/muse/output/cameraroll/schemas/SINK/cameraroll/gradlew clean
/home/amit/muse/output/cameraroll/schemas/SINK/cameraroll/gradlew assembleDebug
cd /home/amit/muse/output/cameraroll/schemas/REACHABILITY/cameraroll/
/home/amit/muse/output/cameraroll/schemas/REACHABILITY/cameraroll/gradlew clean
/home/amit/muse/output/cameraroll/schemas/REACHABILITY/cameraroll/gradlew assembleDebug
cd /home/amit/muse/output/cameraroll/schemas/TAINTSINK/cameraroll/
/home/amit/muse/output/cameraroll/schemas/TAINTSINK/cameraroll/gradlew clean
/home/amit/muse/output/cameraroll/schemas/TAINTSINK/cameraroll/gradlew assembleDebug
cd /home/amit/muse/output/cameraroll/schemas/COMPLEXREACHABILITY/cameraroll/
/home/amit/muse/output/cameraroll/schemas/COMPLEXREACHABILITY/cameraroll/gradlew clean
/home/amit/muse/output/cameraroll/schemas/COMPLEXREACHABILITY/cameraroll/gradlew assembleDebug
