/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.openintents.notepad;

public final class R {
    public static final class array {
        public static final int about_artists=0x7f060002;
        public static final int about_authors=0x7f060003;
        /**  Add your name here if you helped out 
 <item></item> 
         */
        public static final int about_documenters=0x7f060004;
        /**  Add your name here if you helped out, but only in the arrays.xml for the localization that you helped to translate into! 
 <item></item>  
         */
        public static final int about_translators=0x7f060005;
        public static final int preference_fontsize_entries=0x7f060000;
        public static final int preference_fontsize_entryvalues=0x7f060006;
        public static final int preference_sortorder_entries=0x7f060001;
        public static final int preference_sortorder_entryvalues=0x7f060007;
    }
    public static final class attr {
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int background=0x7f010000;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int backgroundPadding=0x7f010001;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int backgroundPaddingBottom=0x7f010005;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int backgroundPaddingLeft=0x7f010002;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int backgroundPaddingRight=0x7f010004;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int backgroundPaddingTop=0x7f010003;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int lineColor=0x7f010007;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int lineMode=0x7f010006;
        /** <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int textColor=0x7f01000e;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int textSizeLarge=0x7f01000d;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int textSizeMedium=0x7f01000c;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int textSizeSmall=0x7f01000b;
        /** <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int textSizeTiny=0x7f01000a;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int textTypeface=0x7f010008;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int textUpperCaseFont=0x7f010009;
    }
    public static final class drawable {
        public static final int ic_delete=0x7f020000;
        public static final int ic_launcher_folder_small=0x7f020001;
        public static final int ic_launcher_notepad=0x7f020002;
        public static final int ic_menu_add_note=0x7f020003;
        public static final int ic_menu_back=0x7f020004;
        public static final int ic_menu_edit=0x7f020005;
        public static final int ic_menu_folder=0x7f020006;
        public static final int ic_menu_forward=0x7f020007;
        public static final int ic_menu_save=0x7f020008;
    }
    public static final class id {
        public static final int background=0x7f0a0003;
        public static final int btnBackward=0x7f0a001a;
        public static final int btnClose=0x7f0a001b;
        public static final int btnForward=0x7f0a0019;
        public static final int button1=0x7f0a000e;
        public static final int button2=0x7f0a0010;
        public static final int buttonbar=0x7f0a0016;
        public static final int check1=0x7f0a0005;
        public static final int container1=0x7f0a0012;
        public static final int container2=0x7f0a000d;
        public static final int edit=0x7f0a0000;
        public static final int edtSearchWord=0x7f0a0018;
        public static final int empty=0x7f0a0009;
        public static final int file_manager=0x7f0a0002;
        public static final int file_path=0x7f0a0001;
        public static final int imageview=0x7f0a0013;
        public static final int info=0x7f0a000b;
        public static final int list1=0x7f0a0004;
        public static final int note=0x7f0a0007;
        public static final int ok=0x7f0a001c;
        public static final int scroll=0x7f0a0006;
        public static final int search=0x7f0a0017;
        public static final int space=0x7f0a000f;
        public static final int status=0x7f0a000c;
        public static final int tagselection=0x7f0a0008;
        public static final int text=0x7f0a0015;
        public static final int text1=0x7f0a0011;
        public static final int text2=0x7f0a0014;
        public static final int title=0x7f0a000a;
    }
    public static final class layout {
        public static final int dialog_edit_tags=0x7f030000;
        public static final int dialog_filename=0x7f030001;
        public static final int dialog_theme_settings=0x7f030002;
        public static final int note_editor=0x7f030003;
        public static final int noteslist=0x7f030004;
        public static final int noteslist_item=0x7f030005;
        public static final int oi_distribution_buttonbar=0x7f030006;
        public static final int oi_distribution_eula=0x7f030007;
        public static final int oi_distribution_infoactivity=0x7f030008;
        public static final int search_toolbar=0x7f030009;
        public static final int title_editor=0x7f03000a;
    }
    public static final class plurals {
        public static final int word_count=0x7f070000;
    }
    public static final class raw {
        public static final int license_short=0x7f050000;
        public static final int oi_distribution_buttonbar=0x7f050001;
        public static final int recent_changes=0x7f050002;
    }
    public static final class string {
        public static final int about_comments=0x7f080000;
        public static final int about_copyright=0x7f08009b;
        public static final int about_email=0x7f08009c;
        public static final int about_translators=0x7f080001;
        public static final int about_website_url=0x7f08009d;
        public static final int all_notes=0x7f080002;
        public static final int already_encrypted=0x7f080003;
        public static final int app_name=0x7f080004;
        public static final int button_dont_save=0x7f080005;
        public static final int button_ok=0x7f080006;
        public static final int button_save=0x7f080007;
        public static final int cancel=0x7f080008;
        public static final int confirm_delete=0x7f080009;
        public static final int confirm_delete_title=0x7f08000a;
        public static final int contact_support=0x7f08009e;
        public static final int decryption_failed=0x7f08000b;
        public static final int decryption_failed_due_to_permissions=0x7f08009f;
        public static final int dropdown_hint=0x7f08000c;
        public static final int empty_note=0x7f08000d;
        public static final int encrypted=0x7f08000e;
        public static final int encrypting_note=0x7f08000f;
        public static final int encryption_failed=0x7f080010;
        public static final int error_message=0x7f080011;
        public static final int error_reading_file=0x7f080012;
        public static final int error_title=0x7f080013;
        public static final int error_writing_file=0x7f080014;
        public static final int file_not_found=0x7f080015;
        public static final int filename=0x7f080016;
        public static final int get_more_themes=0x7f080017;
        public static final int menu_decrypt=0x7f080018;
        public static final int menu_delete=0x7f080019;
        public static final int menu_discard=0x7f08001a;
        public static final int menu_do_not_encrypt=0x7f08001b;
        public static final int menu_edit_tags=0x7f08001c;
        public static final int menu_encrypt=0x7f08001d;
        public static final int menu_import=0x7f08001e;
        public static final int menu_insert=0x7f08001f;
        public static final int menu_open_from_sdcard=0x7f080020;
        public static final int menu_revert=0x7f080021;
        public static final int menu_save=0x7f080022;
        public static final int menu_save_as=0x7f080023;
        public static final int menu_save_to_sdcard=0x7f080024;
        public static final int menu_search=0x7f080025;
        public static final int menu_share=0x7f080026;
        public static final int menu_theme=0x7f080027;
        public static final int menu_undo_encryption=0x7f080028;
        public static final int menu_upload=0x7f0800a0;
        public static final int menu_word_count=0x7f080029;
        public static final int new_note=0x7f08002a;
        public static final int no_notes=0x7f08002b;
        public static final int no_notes_actionbar=0x7f08002c;
        public static final int not_encrypted=0x7f08002d;
        public static final int note_editor_preferences=0x7f08002e;
        public static final int note_saved=0x7f08002f;
        public static final int noteslist_preferences=0x7f080030;
        public static final int oi_distribution_about=0x7f080031;
        public static final int oi_distribution_aboutapp=0x7f080032;
        public static final int oi_distribution_aboutapp_get=0x7f080033;
        public static final int oi_distribution_aboutapp_not_available=0x7f080034;
        public static final int oi_distribution_aboutapp_package=0x7f0800a1;
        public static final int oi_distribution_aboutapp_website=0x7f0800a2;
        public static final int oi_distribution_app_name=0x7f080035;
        public static final int oi_distribution_barcodescanner=0x7f080036;
        public static final int oi_distribution_barcodescanner_not_available=0x7f080037;
        public static final int oi_distribution_barcodescanner_package=0x7f0800a3;
        public static final int oi_distribution_barcodescanner_website=0x7f0800a4;
        public static final int oi_distribution_browser_error=0x7f0800a5;
        public static final int oi_distribution_download_market=0x7f080038;
        public static final int oi_distribution_download_market_message=0x7f080039;
        public static final int oi_distribution_download_message=0x7f08003a;
        public static final int oi_distribution_download_title=0x7f08003b;
        public static final int oi_distribution_download_web=0x7f08003c;
        public static final int oi_distribution_eula_accept=0x7f08003d;
        public static final int oi_distribution_eula_message=0x7f08003e;
        public static final int oi_distribution_eula_refuse=0x7f08003f;
        public static final int oi_distribution_eula_title=0x7f080040;
        public static final int oi_distribution_filemanager=0x7f080041;
        public static final int oi_distribution_filemanager_not_available=0x7f080042;
        public static final int oi_distribution_filemanager_package=0x7f0800a6;
        public static final int oi_distribution_filemanager_website=0x7f0800a7;
        public static final int oi_distribution_info_activity_text=0x7f080043;
        public static final int oi_distribution_info_instructions=0x7f080044;
        public static final int oi_distribution_info_launch=0x7f080045;
        public static final int oi_distribution_info_not_available=0x7f080046;
        public static final int oi_distribution_launch_error=0x7f080047;
        public static final int oi_distribution_menu_update=0x7f080048;
        public static final int oi_distribution_name_and_version=0x7f080049;
        public static final int oi_distribution_newversion_continue=0x7f08004a;
        public static final int oi_distribution_newversion_message=0x7f08004b;
        public static final int oi_distribution_newversion_recent_changes=0x7f08004c;
        public static final int oi_distribution_privacy=0x7f0800a8;
        public static final int oi_distribution_safe=0x7f08004d;
        public static final int oi_distribution_safe_not_available=0x7f08004e;
        public static final int oi_distribution_safe_not_available_decrypt=0x7f08004f;
        public static final int oi_distribution_safe_package=0x7f0800a9;
        public static final int oi_distribution_safe_website=0x7f0800aa;
        public static final int oi_distribution_support=0x7f080050;
        public static final int oi_distribution_supportapp=0x7f080051;
        public static final int oi_distribution_supportapp_get=0x7f080052;
        public static final int oi_distribution_supportapp_not_available=0x7f080053;
        public static final int oi_distribution_update_app=0x7f080054;
        public static final int oi_distribution_update_box_text=0x7f080055;
        public static final int oi_distribution_update_check_now=0x7f080056;
        public static final int oi_distribution_update_checker_package=0x7f0800ab;
        public static final int oi_distribution_update_checker_website=0x7f0800ac;
        public static final int oi_distribution_update_error=0x7f080057;
        public static final int oi_distribution_update_get_updater=0x7f080058;
        public static final int oi_not_now=0x7f0800ad;
        public static final int oi_notepad_permission_read=0x7f080059;
        public static final int oi_notepad_permission_read_descr=0x7f08005a;
        public static final int oi_notepad_permission_write=0x7f08005b;
        public static final int oi_notepad_permission_write_descr=0x7f08005c;
        public static final int oi_open_page=0x7f0800ae;
        public static final int oi_privacy_dialog_title=0x7f0800af;
        public static final int oi_privacy_page=0x7f0800b0;
        public static final int oi_safe_permission_intents=0x7f08005d;
        public static final int oi_safe_permission_intents_descr=0x7f08005e;
        public static final int oi_shopping_permission_read=0x7f08005f;
        public static final int oi_shopping_permission_read_descr=0x7f080060;
        public static final int oi_shopping_permission_write=0x7f080061;
        public static final int oi_shopping_permission_write_descr=0x7f080062;
        public static final int oi_support_dialog_title=0x7f0800b1;
        public static final int oi_support_page=0x7f0800b2;
        public static final int oi_visit_oi_privacy_page=0x7f0800b3;
        public static final int oi_visit_oi_support_page=0x7f0800b4;
        public static final int ok=0x7f080063;
        public static final int open=0x7f080064;
        public static final int preference_addons=0x7f080065;
        public static final int preference_autolink_summary_off=0x7f080066;
        public static final int preference_autolink_summary_on=0x7f080067;
        public static final int preference_autolink_title=0x7f080068;
        public static final int preference_charcount_summary_off=0x7f080069;
        public static final int preference_charcount_summary_on=0x7f08006a;
        public static final int preference_charcount_title=0x7f08006b;
        public static final int preference_developer_extensions_link=0x7f0800b5;
        public static final int preference_developer_extensions_summary=0x7f08006c;
        public static final int preference_developer_themes_link=0x7f0800b6;
        public static final int preference_developer_themes_summary=0x7f08006d;
        public static final int preference_extensions=0x7f08006e;
        public static final int preference_fontsize=0x7f08006f;
        public static final int preference_fontsize_dialog_title=0x7f080070;
        public static final int preference_fontsize_summary=0x7f080071;
        public static final int preference_get_addons=0x7f080072;
        public static final int preference_get_addons_summary=0x7f080073;
        public static final int preference_get_developer_addons=0x7f080074;
        public static final int preference_get_market_addons=0x7f080075;
        public static final int preference_market_extensions_link=0x7f0800b7;
        public static final int preference_market_extensions_summary=0x7f080076;
        public static final int preference_market_themes_link=0x7f0800b8;
        public static final int preference_market_themes_summary=0x7f080077;
        public static final int preference_marquee_summary=0x7f080078;
        public static final int preference_marquee_title=0x7f080079;
        public static final int preference_sortorder_dialog_title=0x7f08007a;
        public static final int preference_sortorder_summary=0x7f08007b;
        public static final int preference_sortorder_title=0x7f08007c;
        public static final int preference_themes=0x7f08007d;
        public static final int request_permissions=0x7f0800b9;
        public static final int resolve_edit=0x7f08007e;
        public static final int resolve_title=0x7f08007f;
        public static final int save=0x7f080080;
        public static final int search_found_no_results=0x7f080081;
        public static final int search_hint=0x7f080082;
        public static final int search_label=0x7f080083;
        public static final int search_query_results=0x7f080084;
        public static final int search_settings_description=0x7f080085;
        public static final int settings=0x7f080086;
        public static final int settings_sortorder=0x7f080087;
        public static final int share_not_available=0x7f080088;
        public static final int tags_hint=0x7f080089;
        public static final int theme_default=0x7f08008a;
        public static final int theme_monospaced=0x7f08008b;
        public static final int theme_pick=0x7f08008c;
        public static final int theme_serif=0x7f08008d;
        public static final int title_create=0x7f08008e;
        public static final int title_create_file=0x7f08008f;
        public static final int title_edit=0x7f080090;
        public static final int title_edit_file=0x7f080091;
        public static final int title_edit_title=0x7f080092;
        public static final int title_note=0x7f080093;
        public static final int title_notes_list=0x7f080094;
        public static final int title_pick_note_for_shortcut=0x7f080095;
        public static final int toast_wrap_bottom=0x7f0800ba;
        public static final int toast_wrap_top=0x7f0800bb;
        public static final int use_theme_for_all_lists=0x7f080096;
        public static final int warning_file_exists_message=0x7f080097;
        public static final int warning_file_exists_title=0x7f080098;
        public static final int warning_unsaved_changes_message=0x7f080099;
        public static final int warning_unsaved_changes_title=0x7f08009a;
    }
    public static final class style {
        public static final int Theme=0x7f090000;
        public static final int Theme_Notepad=0x7f090001;
        public static final int Theme_Notepad_Monospaced=0x7f090002;
        public static final int Theme_Notepad_Serif=0x7f090003;
    }
    public static final class xml {
        public static final int about=0x7f040000;
        public static final int preferences=0x7f040001;
        public static final int searchable=0x7f040002;
        public static final int themes=0x7f040003;
    }
    public static final class styleable {
        /** Attributes that can be used with a Notepad.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #Notepad_background org.openintents.notepad:background}</code></td><td></td></tr>
           <tr><td><code>{@link #Notepad_backgroundPadding org.openintents.notepad:backgroundPadding}</code></td><td></td></tr>
           <tr><td><code>{@link #Notepad_backgroundPaddingBottom org.openintents.notepad:backgroundPaddingBottom}</code></td><td></td></tr>
           <tr><td><code>{@link #Notepad_backgroundPaddingLeft org.openintents.notepad:backgroundPaddingLeft}</code></td><td></td></tr>
           <tr><td><code>{@link #Notepad_backgroundPaddingRight org.openintents.notepad:backgroundPaddingRight}</code></td><td></td></tr>
           <tr><td><code>{@link #Notepad_backgroundPaddingTop org.openintents.notepad:backgroundPaddingTop}</code></td><td></td></tr>
           <tr><td><code>{@link #Notepad_lineColor org.openintents.notepad:lineColor}</code></td><td></td></tr>
           <tr><td><code>{@link #Notepad_lineMode org.openintents.notepad:lineMode}</code></td><td></td></tr>
           <tr><td><code>{@link #Notepad_textColor org.openintents.notepad:textColor}</code></td><td></td></tr>
           <tr><td><code>{@link #Notepad_textSizeLarge org.openintents.notepad:textSizeLarge}</code></td><td></td></tr>
           <tr><td><code>{@link #Notepad_textSizeMedium org.openintents.notepad:textSizeMedium}</code></td><td></td></tr>
           <tr><td><code>{@link #Notepad_textSizeSmall org.openintents.notepad:textSizeSmall}</code></td><td></td></tr>
           <tr><td><code>{@link #Notepad_textSizeTiny org.openintents.notepad:textSizeTiny}</code></td><td></td></tr>
           <tr><td><code>{@link #Notepad_textTypeface org.openintents.notepad:textTypeface}</code></td><td></td></tr>
           <tr><td><code>{@link #Notepad_textUpperCaseFont org.openintents.notepad:textUpperCaseFont}</code></td><td></td></tr>
           </table>
           @see #Notepad_background
           @see #Notepad_backgroundPadding
           @see #Notepad_backgroundPaddingBottom
           @see #Notepad_backgroundPaddingLeft
           @see #Notepad_backgroundPaddingRight
           @see #Notepad_backgroundPaddingTop
           @see #Notepad_lineColor
           @see #Notepad_lineMode
           @see #Notepad_textColor
           @see #Notepad_textSizeLarge
           @see #Notepad_textSizeMedium
           @see #Notepad_textSizeSmall
           @see #Notepad_textSizeTiny
           @see #Notepad_textTypeface
           @see #Notepad_textUpperCaseFont
         */
        public static final int[] Notepad = {
            0x7f010000, 0x7f010001, 0x7f010002, 0x7f010003,
            0x7f010004, 0x7f010005, 0x7f010006, 0x7f010007,
            0x7f010008, 0x7f010009, 0x7f01000a, 0x7f01000b,
            0x7f01000c, 0x7f01000d, 0x7f01000e
        };
        /**
          <p>This symbol is the offset where the {@link org.openintents.notepad.R.attr#background}
          attribute's value can be found in the {@link #Notepad} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name org.openintents.notepad:background
        */
        public static final int Notepad_background = 0;
        /**
          <p>This symbol is the offset where the {@link org.openintents.notepad.R.attr#backgroundPadding}
          attribute's value can be found in the {@link #Notepad} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name org.openintents.notepad:backgroundPadding
        */
        public static final int Notepad_backgroundPadding = 1;
        /**
          <p>This symbol is the offset where the {@link org.openintents.notepad.R.attr#backgroundPaddingBottom}
          attribute's value can be found in the {@link #Notepad} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name org.openintents.notepad:backgroundPaddingBottom
        */
        public static final int Notepad_backgroundPaddingBottom = 5;
        /**
          <p>This symbol is the offset where the {@link org.openintents.notepad.R.attr#backgroundPaddingLeft}
          attribute's value can be found in the {@link #Notepad} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name org.openintents.notepad:backgroundPaddingLeft
        */
        public static final int Notepad_backgroundPaddingLeft = 2;
        /**
          <p>This symbol is the offset where the {@link org.openintents.notepad.R.attr#backgroundPaddingRight}
          attribute's value can be found in the {@link #Notepad} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name org.openintents.notepad:backgroundPaddingRight
        */
        public static final int Notepad_backgroundPaddingRight = 4;
        /**
          <p>This symbol is the offset where the {@link org.openintents.notepad.R.attr#backgroundPaddingTop}
          attribute's value can be found in the {@link #Notepad} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name org.openintents.notepad:backgroundPaddingTop
        */
        public static final int Notepad_backgroundPaddingTop = 3;
        /**
          <p>This symbol is the offset where the {@link org.openintents.notepad.R.attr#lineColor}
          attribute's value can be found in the {@link #Notepad} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name org.openintents.notepad:lineColor
        */
        public static final int Notepad_lineColor = 7;
        /**
          <p>This symbol is the offset where the {@link org.openintents.notepad.R.attr#lineMode}
          attribute's value can be found in the {@link #Notepad} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name org.openintents.notepad:lineMode
        */
        public static final int Notepad_lineMode = 6;
        /**
          <p>This symbol is the offset where the {@link org.openintents.notepad.R.attr#textColor}
          attribute's value can be found in the {@link #Notepad} array.


          <p>Must be a color value, in the form of "<code>#<i>rgb</i></code>", "<code>#<i>argb</i></code>",
"<code>#<i>rrggbb</i></code>", or "<code>#<i>aarrggbb</i></code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name org.openintents.notepad:textColor
        */
        public static final int Notepad_textColor = 14;
        /**
          <p>This symbol is the offset where the {@link org.openintents.notepad.R.attr#textSizeLarge}
          attribute's value can be found in the {@link #Notepad} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name org.openintents.notepad:textSizeLarge
        */
        public static final int Notepad_textSizeLarge = 13;
        /**
          <p>This symbol is the offset where the {@link org.openintents.notepad.R.attr#textSizeMedium}
          attribute's value can be found in the {@link #Notepad} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name org.openintents.notepad:textSizeMedium
        */
        public static final int Notepad_textSizeMedium = 12;
        /**
          <p>This symbol is the offset where the {@link org.openintents.notepad.R.attr#textSizeSmall}
          attribute's value can be found in the {@link #Notepad} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name org.openintents.notepad:textSizeSmall
        */
        public static final int Notepad_textSizeSmall = 11;
        /**
          <p>This symbol is the offset where the {@link org.openintents.notepad.R.attr#textSizeTiny}
          attribute's value can be found in the {@link #Notepad} array.


          <p>Must be a dimension value, which is a floating point number appended with a unit such as "<code>14.5sp</code>".
Available units are: px (pixels), dp (density-independent pixels), sp (scaled pixels based on preferred font size),
in (inches), mm (millimeters).
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name org.openintents.notepad:textSizeTiny
        */
        public static final int Notepad_textSizeTiny = 10;
        /**
          <p>This symbol is the offset where the {@link org.openintents.notepad.R.attr#textTypeface}
          attribute's value can be found in the {@link #Notepad} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name org.openintents.notepad:textTypeface
        */
        public static final int Notepad_textTypeface = 8;
        /**
          <p>This symbol is the offset where the {@link org.openintents.notepad.R.attr#textUpperCaseFont}
          attribute's value can be found in the {@link #Notepad} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name org.openintents.notepad:textUpperCaseFont
        */
        public static final int Notepad_textUpperCaseFont = 9;
    };
}
